# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/charles/ClionProjects/Implied_Price_Engine_All

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/charles/ClionProjects/Implied_Price_Engine_All

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charles/ClionProjects/Implied_Price_Engine_All/CMakeFiles /home/charles/ClionProjects/Implied_Price_Engine_All/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/charles/ClionProjects/Implied_Price_Engine_All/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named IElib

# Build rule for target.
IElib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IElib
.PHONY : IElib

# fast build rule for target.
IElib/fast:
	$(MAKE) -f include/CMakeFiles/IElib.dir/build.make include/CMakeFiles/IElib.dir/build
.PHONY : IElib/fast

#=============================================================================
# Target rules for targets named Create_QuoteStream

# Build rule for target.
Create_QuoteStream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Create_QuoteStream
.PHONY : Create_QuoteStream

# fast build rule for target.
Create_QuoteStream/fast:
	$(MAKE) -f utils/CMakeFiles/Create_QuoteStream.dir/build.make utils/CMakeFiles/Create_QuoteStream.dir/build
.PHONY : Create_QuoteStream/fast

#=============================================================================
# Target rules for targets named mempooltest

# Build rule for target.
mempooltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mempooltest
.PHONY : mempooltest

# fast build rule for target.
mempooltest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/mempooltest.dir/build.make Timed_examples/CMakeFiles/mempooltest.dir/build
.PHONY : mempooltest/fast

#=============================================================================
# Target rules for targets named grouptest

# Build rule for target.
grouptest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grouptest
.PHONY : grouptest

# fast build rule for target.
grouptest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/grouptest.dir/build.make Timed_examples/CMakeFiles/grouptest.dir/build
.PHONY : grouptest/fast

#=============================================================================
# Target rules for targets named gentest

# Build rule for target.
gentest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gentest
.PHONY : gentest

# fast build rule for target.
gentest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/gentest.dir/build.make Timed_examples/CMakeFiles/gentest.dir/build
.PHONY : gentest/fast

#=============================================================================
# Target rules for targets named typetest

# Build rule for target.
typetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 typetest
.PHONY : typetest

# fast build rule for target.
typetest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/typetest.dir/build.make Timed_examples/CMakeFiles/typetest.dir/build
.PHONY : typetest/fast

#=============================================================================
# Target rules for targets named cat2_visitortest

# Build rule for target.
cat2_visitortest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cat2_visitortest
.PHONY : cat2_visitortest

# fast build rule for target.
cat2_visitortest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/cat2_visitortest.dir/build.make Timed_examples/CMakeFiles/cat2_visitortest.dir/build
.PHONY : cat2_visitortest/fast

#=============================================================================
# Target rules for targets named allocatortest

# Build rule for target.
allocatortest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allocatortest
.PHONY : allocatortest

# fast build rule for target.
allocatortest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/allocatortest.dir/build.make Timed_examples/CMakeFiles/allocatortest.dir/build
.PHONY : allocatortest/fast

#=============================================================================
# Target rules for targets named CLlegtest

# Build rule for target.
CLlegtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CLlegtest
.PHONY : CLlegtest

# fast build rule for target.
CLlegtest/fast:
	$(MAKE) -f Timed_examples/CMakeFiles/CLlegtest.dir/build.make Timed_examples/CMakeFiles/CLlegtest.dir/build
.PHONY : CLlegtest/fast

#=============================================================================
# Target rules for targets named QuoteClient

# Build rule for target.
QuoteClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuoteClient
.PHONY : QuoteClient

# fast build rule for target.
QuoteClient/fast:
	$(MAKE) -f Quote_Server/CMakeFiles/QuoteClient.dir/build.make Quote_Server/CMakeFiles/QuoteClient.dir/build
.PHONY : QuoteClient/fast

#=============================================================================
# Target rules for targets named QuoteServer

# Build rule for target.
QuoteServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QuoteServer
.PHONY : QuoteServer

# fast build rule for target.
QuoteServer/fast:
	$(MAKE) -f Quote_Server/CMakeFiles/QuoteServer.dir/build.make Quote_Server/CMakeFiles/QuoteServer.dir/build
.PHONY : QuoteServer/fast

#=============================================================================
# Target rules for targets named Threadpool_test

# Build rule for target.
Threadpool_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Threadpool_test
.PHONY : Threadpool_test

# fast build rule for target.
Threadpool_test/fast:
	$(MAKE) -f reg_test/CMakeFiles/Threadpool_test.dir/build.make reg_test/CMakeFiles/Threadpool_test.dir/build
.PHONY : Threadpool_test/fast

#=============================================================================
# Target rules for targets named SecPair_test

# Build rule for target.
SecPair_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SecPair_test
.PHONY : SecPair_test

# fast build rule for target.
SecPair_test/fast:
	$(MAKE) -f reg_test/CMakeFiles/SecPair_test.dir/build.make reg_test/CMakeFiles/SecPair_test.dir/build
.PHONY : SecPair_test/fast

#=============================================================================
# Target rules for targets named ImpliedEngine_test

# Build rule for target.
ImpliedEngine_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ImpliedEngine_test
.PHONY : ImpliedEngine_test

# fast build rule for target.
ImpliedEngine_test/fast:
	$(MAKE) -f reg_test/CMakeFiles/ImpliedEngine_test.dir/build.make reg_test/CMakeFiles/ImpliedEngine_test.dir/build
.PHONY : ImpliedEngine_test/fast

#=============================================================================
# Target rules for targets named Clienttest

# Build rule for target.
Clienttest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Clienttest
.PHONY : Clienttest

# fast build rule for target.
Clienttest/fast:
	$(MAKE) -f reg_test/CMakeFiles/Clienttest.dir/build.make reg_test/CMakeFiles/Clienttest.dir/build
.PHONY : Clienttest/fast

#=============================================================================
# Target rules for targets named SecPair_gtest

# Build rule for target.
SecPair_gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SecPair_gtest
.PHONY : SecPair_gtest

# fast build rule for target.
SecPair_gtest/fast:
	$(MAKE) -f gtest/CMakeFiles/SecPair_gtest.dir/build.make gtest/CMakeFiles/SecPair_gtest.dir/build
.PHONY : SecPair_gtest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... IElib"
	@echo "... Create_QuoteStream"
	@echo "... mempooltest"
	@echo "... grouptest"
	@echo "... gentest"
	@echo "... typetest"
	@echo "... cat2_visitortest"
	@echo "... allocatortest"
	@echo "... CLlegtest"
	@echo "... QuoteClient"
	@echo "... QuoteServer"
	@echo "... Threadpool_test"
	@echo "... SecPair_test"
	@echo "... ImpliedEngine_test"
	@echo "... Clienttest"
	@echo "... SecPair_gtest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

